### ISSUE TITLE
some java error  with allocine : java.lang.NullPointerException

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v2#2758]
from several release i get some java error which i don't understand the reason :  here the log with 191eccb

[08:20:23 - main    ] ThreadExecutor: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.moviejukebox.tools.ThreadExecutor.waitForValues(ThreadExecutor.java:276)
	at com.moviejukebox.tools.ThreadExecutor.waitFor(ThreadExecutor.java:292)
	at com.moviejukebox.MovieJukebox.generateLibrary(MovieJukebox.java:1113)
	at com.moviejukebox.MovieJukebox.main(MovieJukebox.java:469)
Caused by: java.lang.NullPointerException
	at com.moviejukebox.allocine.model.AbstractBaseInfos.getUserRating(AbstractBaseInfos.java:67)
	at com.moviejukebox.allocine.model.MovieInfos.getUserRating(MovieInfos.java:106)
	at com.moviejukebox.plugin.AllocinePlugin.updateMovieInfo(AllocinePlugin.java:263)
	at com.moviejukebox.plugin.AllocinePlugin.scan(AllocinePlugin.java:233)
	at com.moviejukebox.plugin.DatabasePluginController.scan(DatabasePluginController.java:118)
	at com.moviejukebox.MovieJukebox.updateMovieData(MovieJukebox.java:2054)
	at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:1003)
	at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:984)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.moviejukebox.tools.ThreadExecutor$ScheduledThread.run(ThreadExecutor.java:129)

**Comment by Omertron** [comment]
fixed in latest yamj build

**Comment by jluc2808** [comment]
still an error 
strange the version number is still the same 191eccb
[16:28:23 - main    ] ThreadExecutor: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.Double
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.moviejukebox.tools.ThreadExecutor.waitForValues(ThreadExecutor.java:276)
	at com.moviejukebox.tools.ThreadExecutor.waitFor(ThreadExecutor.java:292)
	at com.moviejukebox.MovieJukebox.generateLibrary(MovieJukebox.java:1113)
	at com.moviejukebox.MovieJukebox.main(MovieJukebox.java:469)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.Double
	at java.lang.Class.cast(Unknown Source)
	at com.moviejukebox.allocine.model.Statistics.getStatistic(Statistics.java:67)
	at com.moviejukebox.allocine.model.Statistics.getDoubleStatistic(Statistics.java:62)
	at com.moviejukebox.allocine.model.AbstractBaseInfos.getUserRating(AbstractBaseInfos.java:67)
	at com.moviejukebox.allocine.model.MovieInfos.getUserRating(MovieInfos.java:106)
	at com.moviejukebox.plugin.AllocinePlugin.updateMovieInfo(AllocinePlugin.java:263)
	at com.moviejukebox.plugin.AllocinePlugin.scan(AllocinePlugin.java:233)
	at com.moviejukebox.plugin.DatabasePluginController.scan(DatabasePluginController.java:118)
	at com.moviejukebox.MovieJukebox.updateMovieData(MovieJukebox.java:2054)
	at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:1003)
	at com.moviejukebox.MovieJukebox$3.call(MovieJukebox.java:984)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.moviejukebox.tools.ThreadExecutor$ScheduledThread.run(ThreadExecutor.java:129)

**Comment by Omertron** [comment]
Ok, try the next build. The build version number will not change because the yamjv2 code has not changed, just the allocine code
